#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

echo "======================================"
echo " OSU Kiosk - Oczekiwanie na dysk USB  "
echo "======================================"

mkdir -p /mnt/boot
WAIT=0

while ! mount -L OSUBOOT /mnt/boot 2>/dev/null; do
    sleep 1
    WAIT=$((WAIT+1))
    if [ $WAIT -gt 15 ]; then
        echo "FATAL ERROR: Pendrive OSUBOOT nie zostal wykryty!"
        echo "Wchodze w tryb ratunkowy..."
        exec sh
    fi
done

echo "USB znalezione. Kopiowanie systemu do RAM..."
cp /mnt/boot/rootfs.squashfs /tmp/ || { echo "FATAL ERROR: Brak pliku rootfs.squashfs!"; exec sh; }

echo "Montowanie SquashFS..."
mkdir -p /mnt/root
mount -t squashfs -o loop /tmp/rootfs.squashfs /mnt/root || { echo "FATAL ERROR: Blad SquashFS!"; exec sh; }

umount /mnt/boot

echo "Przelaczanie na glowny system (switch_root)..."
exec switch_root /mnt/root /sbin/init || { echo "FATAL ERROR: switch_root zawiodl!"; exec sh; }
